# generate settings
name: base7
gpu_ids: [0]
train: ~

# datasets
datasets:
  train:
    dataroot_HR: data/DIV2K/DIV2K_train_HR
    dataroot_LR: data/DIV2K/DIV2K_train_LR_bicubic/X2
    filename_path: data/DIV2K_train.txt
    patch_size: 64
    batch_size: 16
    flip: true
    rot: true
    enlarge_times: 20
  val:
    dataroot_HR: data/DIV2K/DIV2K_valid_HR
    dataroot_LR: data/DIV2K/DIV2K_valid_LR_bicubic/X2
    filename_path: data/DIV2K_val.txt
    enlarge_times: 1

# networks
networks:
  which_model: base7
  scale: 2
  in_channels: 3
  num_fea: 28
  m: 4
  out_channels: 3

# path to save
paths:
  experiment_root: ./experiment

# optimizer
solver:
  lr_steps:
    - 120
    - 240
    - 360
    - 480
  lr_gamma: !!float 0.5
  loss: mae
  epochs: 600
  workers: 8
  val_step: 1
  resume_path: experiment/base7_D4C28_bs16ps64_lr1e-3-abc/best_status/
  qat_path: ~
